name: Build Windows

on:
  push:
    paths:
      - '.github/workflows/windows.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        run: choco install ninja

      - name: Download Skia
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/aseprite/skia/releases/download/m102-861e474326/Skia-Windows-Release-x64.zip" -OutFile "skia.zip"
          Expand-Archive -Path "skia.zip" -DestinationPath "skia"

      - name: Compile Aseprite
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_SCRIPTING=ON -DSKIA_DIR=..\skia -DSKIA_LIBRARY_DIR=..\skia\out\Release-x64 -DSKIA_LIBRARY=..\skia\out\Release-x64\skia.lib ..
          ninja aseprite

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Windows
          path: build/bin/aseprite.exe
