name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Ninja
        run: choco install ninja

      - name: Setup Skia
        uses:aseprite/setup-skia@main
        with:
          skia-version: 'm102-861e474326'

      - name: Compile
        run: |
          mkdir build
          cd build
          cmake -G Ninja .. -DENABLE_SCRIPTING=ON -DSKIA_DIR=${{ steps.setup-skia.outputs.skia-dir }} -DSKIA_LIBRARY_DIR=${{ steps.setup-skia.outputs.skia-dir }}/out/Release-x64 -DSKIA_LIBRARY=${{ steps.setup-skia.outputs.skia-dir }}/out/Release-x64/skia.lib
          ninja aseprite

      - uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Windows
          path: build/bin/aseprite.exe
